// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Suite.Recipes/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Suite.Recipes',
  (class Recipes extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../../package.json'))
);
