// generated by Neptune Namespaces v4.x.x
// file: Art.Suite.Recipes/index.js

(module.exports = require('./namespace'))

.addModules({
  AppKitClient:   require('./AppKitClient'),
  StandardImport: require('./StandardImport')
});