// generated by Neptune Namespaces v4.x.x
// file: Art.Suite.Recipes/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Suite.Recipes',
  (class Recipes extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
